Review Kafka Library Usage
iwanjunaid/basesvc pull request #16
Opened 2020-10-27 03:34 UTC by wibiaris

- producer kafka
- consumer kafka

2020-10-31 11:29 UTC, iwanjunaid requested changes

2020-10-31 11:29 UTC, iwanjunaid commented on adapter/controller/author.go
> +	InsertAuthorDocument(author *model.Author) error
ini kalau namanya lebih common lagi tanpa nyebutin jenis datanya (document), misal jadi CreateAuthor() gmana mas?

2020-10-31 11:29 UTC, iwanjunaid commented on adapter/repository/author.go
> +func (author *AuthorRepositoryImpl) InsertDocument(ctx context.Context) error {
Kalau nama methodnya diganti Create() gmana mas, jadi lebih terasa CRUD-nya

2020-10-31 11:29 UTC, iwanjunaid commented on adapter/repository/author.go
> +func (author *AuthorRepositoryImpl) Publish(ctx context.Context, topic string, message []byte) (err error) {
jika kita mau ngirim dengan ```message key```, gmana mas? artinya ```message_key``` sifatnya optional?

2020-10-31 11:29 UTC, iwanjunaid commented on adapter/repository/mongodb/mongodb.go
> +type AuthorRepositoryReaderImpl struct {
Mas mending AuthorRepository-nya jgn dipisah berdasarkan data storenya, jadi tetap aja seperti yg lama tp ditambahi referensi ke mongo-db:

```
type AuthorRepositoryImpl struct {
	db *sql.DB,
        mdb *mongo.Database,
}
```

2020-10-31 11:29 UTC, iwanjunaid commented on cmd/consumer.go
> +		consumer.NewConsumer(kc, db).Listen(config.GetString("kafka.topio"))
typo mas?

2020-10-31 11:29 UTC, iwanjunaid commented on infrastructure/consumer/consumer.go
> +func (c *ConsumerImpl) Listen(topic string) {
Jika ingin listen banyak topic, caranya gmana mas?

2020-10-31 11:29 UTC, iwanjunaid commented on usecase/author/repository/author.go
> +	InsertDocument(ctx context.Context) error
namanya biar lebih common, bisa diubah ke Create() gak mas?

2020-11-02 09:22 UTC, wibiaris commented on adapter/repository/author.go
> +func (author *AuthorRepositoryImpl) InsertDocument(ctx context.Context) error {
klo Create, gak bisa bedain dong mas function untuk `create` postgresql dan mongodb

2020-11-02 09:26 UTC, wibiaris commented on adapter/repository/author.go
> +func (author *AuthorRepositoryImpl) Publish(ctx context.Context, topic string, message []byte) (err error) {
message key itu apa yak ? message parameter disini artinya payload dari json struct yang di konversi ke tipe byte  mas

2020-11-02 09:27 UTC, wibiaris commented on infrastructure/consumer/consumer.go
> +func (c *ConsumerImpl) Listen(topic string) {
ada kebutuhan untuk subscribe/listen lebih dari 1 topic ?

2020-11-05 01:42 UTC, iwanjunaid requested changes

2020-11-05 01:42 UTC, iwanjunaid commented on infrastructure/consumer/consumer.go
> +func (c *ConsumerImpl) Listen(topic string) {
Iya mas, bisa jadi consume ke lebih satu topic

2020-11-07 04:48 UTC, ilmimris commented on adapter/repository/author.go
> +func (author *AuthorRepositoryImpl) InsertDocument(ctx context.Context) error {
jadi kalau `create` hanya untuk sql aja ya?

2020-11-09 00:40 UTC, merged