Add gravatar example resty request to public API
iwanjunaid/basesvc pull request #40
Opened 2020-11-10 00:42 UTC by ilmimris

Why resty? --> [docs](https://github.com/go-resty/resty)

Contoh ini hanya mengimplementasikan method **GET** dengan **redirect policy allowed**

2020-11-10 03:15 UTC, iwanjunaid requested changes, later dismissed

2020-11-10 03:15 UTC, iwanjunaid commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/go,code
Ini buat apa ya mas @ilmimris ?

2020-11-10 04:41 UTC, ilmimris commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/go,code
ga buat apa-apa mas, itu cuma komentar doang, karena dulu buat .gitignorenya di generate dari web tsb

2020-11-10 04:58 UTC, iwanjunaid reviewed
LGTM

2020-11-11 08:01 UTC, wibiaris approved these changes
LGTM

2020-11-12 01:03 UTC, merged