Simplify rest endpoints
iwanjunaid/basesvc pull request #5
Opened 2020-10-22 12:59 UTC by iwanjunaid

2020-10-22 13:19 UTC, ilmimris requested changes

2020-10-22 13:19 UTC, ilmimris commented on adapter/controller/author.go
> +
Bukannya udah setuju ya kalau empty result itu tetep balikannya 200?

2020-10-22 13:19 UTC, ilmimris commented on infrastructure/rest/rest.go
> +}
Ini waktu init router kan? 
Komentar deskripsi untuk API-nya yang sebelumnya dihapus? Komentar itu perlu untuk membuat dokumentasi swagger secara otomatis.

2020-10-22 13:25 UTC, ilmimris requested changes

2020-10-22 13:25 UTC, ilmimris commented on infrastructure/rest/rest.go
> +}
Contoh komentarnya seperti ini
```Go
// @title BaseSVC API
// @version 1.0
// @description This is a sample basesvc server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /v1
```

2020-10-22 15:05 UTC, wibiaris commented on infrastructure/rest/middleware/authentication.go
> +		// Implement your authentication here
perlu authentikasi di level service ?

2020-10-22 15:05 UTC, wibiaris commented on cmd/version.go
> +	Use:   "version",
perlu banget pakai command version @iwanjunaid ? gak cukup di version tagging repository aja  yak?

2020-10-22 15:05 UTC, wibiaris commented on infrastructure/rest/handler/v1/author/update.go
> +func Update(rest interfaces.Rest) func(*fiber.Ctx) error {
mending handler dan controller jadi 1 aja kali ya ? biar lebih simple

2020-10-23 00:56 UTC, iwanjunaid commented on adapter/controller/author.go
> +
Haha iya kelupaan

2020-10-23 00:57 UTC, iwanjunaid commented on infrastructure/rest/rest.go
> +}
kalau BasePath-nya ada 2, misal /v1 dan /v2 apakah title, version dan descriptionnya sama?

2020-10-23 00:59 UTC, iwanjunaid commented on infrastructure/rest/middleware/authentication.go
> +		// Implement your authentication here
gak perlu sih. cuma nanti kalau gak jadi pake API Gateway 3rd party, rencana pake service sendiri yg perlu authentication. Jadi sementara memang ini dikosongkan untuk tujuan contoh saja.

2020-10-23 00:59 UTC, iwanjunaid commented on cmd/version.go
> +	Use:   "version",
ok yg ini saya hilangkan ya

2020-10-23 01:01 UTC, iwanjunaid commented on infrastructure/rest/handler/v1/author/update.go
> +func Update(rest interfaces.Rest) func(*fiber.Ctx) error {
kalau saya mending terpisah, krn jaga2 jika implementasi masing2 handler ternyata memiliki banyak baris. @wibiaris

2020-10-23 01:34 UTC, iwanjunaid commented on infrastructure/rest/handler/v1/author/update.go
> +func Update(rest interfaces.Rest) func(*fiber.Ctx) error {
dan juga tiap handler nanti pasti ada swagger doc, jadi nambah bikin panjang lagi mas

2020-10-23 03:47 UTC, merged