feat: data cache on redis
iwanjunaid/basesvc pull request #55
Opened 2020-11-19 03:02 UTC by ilmimris

2020-11-20 02:22 UTC, ilmimris commented
Sudah di test dan berhasil get and set ke redis

2020-11-23 01:17 UTC, iwanjunaid requested changes

2020-11-23 01:17 UTC, iwanjunaid commented on Makefile
> +	go build CGO_ENABLED=0 GOOS=linux go build -a -tags musl -installsuffix cgo -ldflags '-extldflags "-static"' -o ${BINARY}
@ilmimris yg terakhir dicoba, line 6 error

2020-11-23 02:34 UTC, iwanjunaid approved these changes
LGTM

2020-11-23 03:53 UTC, MarthaSutopo13 approved these changes
Sipp mas

2020-11-24 02:44 UTC, wibiaris approved these changes
LGTM

2020-11-24 02:49 UTC, merged