fix telemetry instrumentation
iwanjunaid/basesvc pull request #64
Opened 2020-11-24 14:02 UTC by wibiaris

fix telemetry instrumentation

2020-11-25 02:10 UTC, ilmimris approved these changes

2020-11-25 03:29 UTC, iwanjunaid requested changes

2020-11-25 03:29 UTC, iwanjunaid commented on internal/telemetry/telemetry.go
> +		DatabaseName:       "basesvc",
mas ```Host``` dan ```DatabaseName``` apakah perlu di-hard-coded?

2020-11-26 02:36 UTC, iwanjunaid approved these changes
LGTM

2020-11-26 02:36 UTC, merged