wip: implement NoticeError NR
iwanjunaid/basesvc pull request #69
Opened 2020-12-01 09:39 UTC by ilmimris

2020-12-03 08:12 UTC, wibiaris approved these changes
LGTM

2020-12-03 08:46 UTC, MarthaSutopo13 requested changes
Lbh baik nilai constant di buat 1 file terpisah dan tidak dicampur difile ini. Saya sempat bikin package shared. Mngkin d dlm package share bs buat folder lg dan file sesuai kebutuhan mas

2020-12-03 08:46 UTC, MarthaSutopo13 commented on adapter/repository/sql/postgres.go
> +const (
Lbh baik nilai constant di buat 1 file terpisah dan tidak dicampur difile ini. Saya sempat bikin package shared. Mngkin d dlm package share bs buat folder lg dan file sesuai kebutuhan mas.

2020-12-04 01:38 UTC, ilmimris commented on adapter/repository/sql/postgres.go
> +const (
Oke, setuju mba @MarthaSutopo13

2020-12-04 06:13 UTC, MarthaSutopo13 approved these changes
LGTM

2020-12-04 22:19 UTC, merged