Feature/mokabox
iwanjunaid/basesvc pull request #90
Opened 2020-12-18 09:30 UTC by wibiaris

- initial command mokabox ,outbox pattern in basesvc service

2020-12-18 10:19 UTC, ilmimris requested changes

2020-12-18 10:19 UTC, ilmimris commented on infrastructure/mokabox/mokabox.go
> +	var httpPort = ":8080"
ini ga baca dari config aja mas? takutnya kalau di hardcoded gini port 8080 used jadi ga jalan mokaboxnya trus harus ubah codenya.

2020-12-18 10:19 UTC, ilmimris commented on infrastructure/mokabox/mokabox.go
> +		fmt.Println("Listening on http://0.0.0.0:8080")
string msg-nya ga di construct dari `httpPort` mas?

2020-12-18 10:25 UTC, wibiaris commented on infrastructure/mokabox/mokabox.go
> +	var httpPort = ":8080"
Harusnya enggak bentrok mi, cuma 1 http server aja di 1 pod, krn per command untuk 1 pod aja

2020-12-18 10:25 UTC, wibiaris commented on infrastructure/mokabox/mokabox.go
> +		fmt.Println("Listening on http://0.0.0.0:8080")
Bisa, ini cuma utk logging aja sebenarnya, nanti aku update. Thank u

2020-12-21 02:49 UTC, iwanjunaid approved these changes

2020-12-21 06:46 UTC, merged